name: 'dbt_root'
version: '1.0.0'
config-version: 2

# This dbt project combines multiple workflows:
# - wf_AM_DI_CUSTOMER
# - wf_AP_FF_CITIBANK_VCA
# - wf_BL_FF_ZJ_JOURNALS
# - wf_BL_FF_ZJ_JOURNALS_STG
# - wf_CM_Z1_DAILY_SALES_FEED
# - wf_DI_ITEM_MTRL_MASTER
# - wf_FF_AT_Z1_GL_ACCOUNT
# - wf_FF_AT_ZJ_GL_ACCOUNT
# - wf_S_BP_ARURHD


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_root:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

vars:
  # Workflow parameters
  param_sq_override: ""
  param_sq_filter: ""
  param_src_pre_sql: ""
  param_src_post_sql: ""
  param_tgt_pre_sql: ""
  param_tgt_post_sql: ""