name: dbt_my_dbt_project
version: 1.0.0
config-version: 2
profile: dbt_my_dbt_project
model-paths:
- models
analysis-paths:
- analyses
test-paths:
- tests
seed-paths:
- seeds
macro-paths:
- macros
snapshot-paths:
- snapshots
target-path: target
clean-targets:
- target
- dbt_packages
models:
  dbt_my_dbt_project:
    staging:
      +materialized: view
      +docs:
        node_color: lightblue
    intermediate:
      +materialized: view
      +docs:
        node_color: orange
    marts:
      +materialized: table
      +docs:
        node_color: green
vars:
  param_sq_override: ''
  param_sq_filter: ''
  param_src_pre_sql: ''
  param_src_post_sql: ''
  param_tgt_pre_sql: TRUNCATE TABLE {{ this }}
  param_tgt_post_sql: ''
  param_src_tbl_nme1: CUST_MASTER
  param_src_tbl_nme2: CUST_ADRS
  param_src_tbl_nme3: PTNR_FCTN
  param_tgt_tbl_nme: CUSTOMER
  param_lkp_tbl_nme1: BUS_PTNR_IDS
  param_lkp_override_bus_ptnr_ids: ''
  source_schema: RAW_DATA
  source_database: TPC_DI_RAW_DATA
  target_schema: ANALYTICS
  start_date: '2024-01-01'
  batch_size: 10000
  error_threshold: 0
seeds:
  dbt_my_dbt_project:
    +quote_columns: false
