version: 2

models:
  - name: stg_t_ap_citibank_vca
    description: "Staging model for Citibank VCA source data"
    columns:
      - name: action_type
        description: "Type of action being performed"
      - name: record_id
        description: "Unique record identifier"
        tests:
          - not_null
      - name: issuer_id
        description: "Card issuer identifier"
      - name: ica_nbr
        description: "ICA number"
      - name: bank_nbr
        description: "Bank number"
      - name: user_name
        description: "User name"
      - name: request_id
        description: "Request identifier"
      - name: min_purchase_amt
        description: "Minimum purchase amount"
      - name: max_purchase_amt
        description: "Maximum purchase amount"
      - name: purchase_currency
        description: "Purchase currency"
      - name: purchase_type
        description: "Purchase type"
      - name: v_card_alias
        description: "Virtual card alias"
      - name: supplier_name
        description: "Supplier name"
      - name: supplier_email
        description: "Supplier email"
      - name: multi_use
        description: "Multi-use flag"
      - name: valid_from
        description: "Validity start date"
      - name: valid_to
        description: "Validity end date"
      - name: valid_for
        description: "Validity period"
      - name: cdf_payment_number
        description: "CDF payment number"
      - name: cdf_payee_number
        description: "CDF payee number"
      - name: cdf_payment_amount
        description: "CDF payment amount"
      - name: cdf_payment_date
        description: "CDF payment date"
      - name: cdf_payee_name
        description: "CDF payee name"
      - name: etl_load_dte
        description: "ETL load timestamp"