-- Source: wf_CM_Z1_DAILY_SALES_FEED.XML
-- Staging model for T_CM_Z1_SALES
-- Applies basic data cleaning and standardization

select
    t_cm_z1_sales_id,
    ordernumber,
    lineitemnumber,
    invoicenumber,
    invoicedate,
    sourcesystem,
    businesssegment,
    businesssegmentdescription,
    surgerydate,
    customernumber,
    customernumbershipto,
    customername,
    txncustomernumber,
    txncustomername,
    customerpattern,
    customerpo,
    surgeonid,
    surgeonname,
    txnsurgeonid,
    txnsurgeonname,
    itemnumber,
    itemdescription,
    salesadjustmentname,
    salesadjustmenttype,
    rafinvoicedate,
    itemclass,
    itemclassdescription,
    unitsaleprice,
    quantityshipped,
    unitlistprice,
    county,
    txncounty,
    countydescription,
    territoryid,
    trxterritoryid,
    trxterritoryname,
    trxsalesrepnumber,
    trxsalesrepname,
    contractnumber,
    contractname,
    pricingpenaltyproration,
    commissioncode,
    ordertype,
    transferordertype,
    transactiontypecode,
    costcenter,
    z_to_zindicator,
    transportationdistributor,
    transportationzimmer,
    acctsreceivablevalue,
    customerfreight,
    restockfee,
    adjdetailreporttablenum,
    specialcharges,
    salestax,
    othertaxes,
    transactionheader,
    customertype,
    etl_md5,
    etl_updt_flg,
    etl_create_dte,
    etl_load_dte,
    shipviadesc,
    sms_case_number,
    trailerrecord_yn
from {{ source('t_cm', 't_cm_z1_sales') }}
{% if var('param_sq_filter', '') != '' %}
where {{ var('param_sq_filter') }}
{% endif %}