-- Model: wf_di_item_mtrl_master_stg_mtrl_master
-- Merged from 2 chunks

{{ config(materialized='view') }}

select
    mtrl_nbr,
    mtrl_desc,
    created_dt,
    last_chg_dt,
    created_by,
    last_chg_usr,
    old_mtrl_nbr,
    basic_mtrl,
    mtrl_tp,
    mtrl_grp,
    entrnl_mtrl_grp,
    lvl_7_cd,
    division_cd,
    industry_sctr,
    base_uom,
    prchs_ordr_uom,
    net_wgt,
    gross_wgt,
    wgt_unit_cd,
    mtrl_vol,
    vol_unit_cd,
    size_dim,
    mtrl_length,
    mtrl_wdth,
    mtrl_hgt,
    x_plnt_mtrl_sts,
    x_plnt_mtrl_sts_dt,
    deletion_flg,
    batch_mgmt_ind,
    srl_nbr_lvl,
    ean_upc_nbr,
    ean_cat,
    mfg_nm,
    mfg_pt_nbr,
    mfg_pt_prfl,
    cntry_of_orgn_cd,
    commodity,
    auth_grp,
    gnrl_item_cat_grp,
    pckng_cd,
    pkgng_mtrl_grp,
    pkgg_mtrl_tp,
    lbl_tp,
    lbl_form,
    hndlng_unit_tp,
    strg_cndtn,
    strg_pctg,
    tmptr_cndtn_ind,
    cntnr_rqrmnts,
    tot_shlf_lf,
    min_shlf_lf,
    sled_rndng_rule,
    sled_period_ind,
    aprvd_btch_rcrd_ind,
    hzrds_mtrl_nbr,
    dcmnt_nbr,
    dcmnt_tp,
    dcmnt_vrsn,
    dcmnt_chng_nbr,
    dcmnt_pg_nbr,
    pg_format,
    lab_dsgn_ofc,
    cad_ind,
    maint_status,
    mtrl_dscnt_ind,
    prchs_ordr_unit_ind,
    prchsg_value_key,
    mtrl_frt_grp,
    uod_value,
    envmnt_rlvnt_ind,
    industry_std_desc,
    gr_gl_slips,
    bulk_lqd_ind,
    hgly_vscs_ind,
    -- Material thickness attributes
    mtrl_thk_ind,
    mtrl_thk_upr_limit,
    mtrl_thk_lwr_limit,
    mtrl_thk_msrmt,
    -- Shipping attributes
    shpng_rstrctn,
    shpng_tmptr_ctrl_ind,
    -- Item indicators
    scrap_itm_ind,
    rebox_ww_ind,
    rebox_nw_ind,
    rebox_id,
    -- Material property indicators
    disposable_ind,
    expiry_ind,
    sterile_ind,
    serialized_ind,
    latex_ind,
    mercury_free_ind,
    hazardous_ind,
    pvc_free_ind,
    dehp_free_ind,
    danger_goods_ind,
    instrmnt_ind,
    rework_ind,
    ce_mark_ind,
    -- PTO attributes
    pto_relevant,
    pto_relevant_qnty,
    -- Export control
    eccn_nbr,
    -- FDA and other codes
    fda_prod_cd,
    hyp_cd,
    hyp_brand_desc,
    -- DPS attributes
    dps_generic_lot,
    dps_uom_qty,
    etl_load_dt
from {{ source('target_system', 'mtrl_master') }}