name: 'dbt_citybank'
version: '1.0.0'
config-version: 2

profile: 'dbt_citybank'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_citybank:
    staging:
      +materialized: view
      +tags: ['staging']
    intermediate:
      +materialized: view
      +tags: ['intermediate']
    marts:
      +materialized: table
      +tags: ['mart']

vars:
  # Date format variables for reusability
  datetime_format: 'YYYY-MM-DD HH24:MI:SS'
  timezone_suffix: '.00 +0000'