-- Source: wf_DI_ITEM_MTRL_MASTER.XML
-- Staging for material master raw data
select
    product,
    mater_grp_pckg_mater as packaging_material_group,
    product_group,
    weight_unit,
    volume_unit,
    material_volume,
    size_or_dimension_text,
    product_hierarchy,
    product_old_id,
    net_weight,
    labdsgnoffc as lab_design_office,
    product_standard_id,
    gross_weight,
    item_category_group,
    external_product_group,
    division,
    cross_plant_status_validity_date,
    cross_plant_status,
    international_article_number_cat,
    authorization_group,
    product_type,
    industry_sector,
    pgenumdocwitho_doc_manasys as page_num_doc_without_doc_mgmt_sys,
    industry_standard_name,
    docverwitho_doc_manasys as doc_version_without_doc_mgmt_sys,
    doctypwitho_doc_manasys as doc_type_without_doc_mgmt_sys,
    docchngenumwithodocumanasys as doc_change_num_without_doc_mgmt_sys,
    cad_indicator,
    basic_material,
    pge_format_produc_memo as page_format_product_memo,
    indi_in_bulk_liquid,
    indi_highly_viscous,
    envrmnt_relevant as environment_relevant,
    docnumwithodocmanagsys as doc_num_without_doc_mgmt_sys,
    pack_code,
    approved_batch_rec_req,
    ttlshelflife as total_shelf_life,
    temppcondindi as temp_condition_indicator,
    strgperc as storage_percentage,
    strcond as storage_condition,
    roundrlcal_sled as round_rule_calc_sled,
    hazardmatnum as hazard_material_number,
    contnrreq as container_requirements,
    prd_indi_exp_dt as product_indicator_expiry_date,
    quant_grgiprnt as quantity_goods_receipt_print,
    min_rem_shelf as minimum_remaining_shelf,
    label_type,
    label_form,
    serial_no_explicitness_level,
    manufacturer_number,
    varbl_pur_ord_unit_is_active as variable_purchase_order_unit_active,
    purchng_val_key as purchasing_value_key,
    materqualdisckind as material_quality_discount_kind,
    purchase_order_quantity_unit,
    manufacturer_part_profile,
    product_manufacturer_number,
    material_frieght_group,
    created_by_user,
    creation_date,
    last_changed_by_user,
    last_change_date,
    base_unit,
    danger_goods_ind,
    is_batch_management_required,
    disposable_ind,
    expiry_ind,
    sterile_ind,
    serialized_ind,
    maint_status,
    commodity,
    country_of_origin_material,
    product_description,
    current_timestamp as etl_load_dt
from {{ source('sap_source', 'material_master_raw') }}