-- Source: wf_DI_ITEM_MTRL_MASTER.XML
-- Staging model for material master lookup data
-- Used for existing record lookups and change detection

select
    material_id,
    material_desc,
    disposable_ind,
    expiry_ind,
    sterile_ind,
    serialized_ind,
    hyp_brand_desc,
    hyp_cd,
    rework_ind,
    rebox_id,
    dps_uom_qty,
    dps_generic_lot,
    fda_prod_cd,
    ce_mark_ind,
    ibp_scope_ind,
    eccn_nbr,
    pto_relevant,
    pto_relevant_qnty,
    hazardous_ind,
    mercury_free_ind,
    latex_ind,
    pvc_free_ind,
    dehp_free_ind,
    danger_goods_ind,
    mtrl_thk_msrmt,
    mtrl_thk_lwr_limit,
    mtrl_thk_upr_limit,
    mtrl_thk_ind,
    shpng_rstrctn,
    instrmnt_ind,
    rebox_nw_ind,
    rebox_ww_ind,
    scrap_itm_ind,
    shpng_tmptr_ctrl_ind,
    record_hash,
    created_date,
    updated_date,
    current_timestamp as loaded_at
from {{ source('lookup_system', 'mtrl_master') }}