-- Source: wf_DI_ITEM_MTRL_MASTER.XML
-- Staging model for XML material attributes
{{ config(materialized='view') }}

select
    product as mtrl_nbr,
    product_description as mtrl_desc,
    creation_date as created_dt,
    last_change_date as last_chg_dt,
    created_by_user as created_by,
    last_changed_by_user as last_chg_usr,
    product_old_id as old_mtrl_nbr,
    basic_material,
    product_type as mtrl_tp,
    product_group as mtrl_grp,
    external_product_group as entrnl_mtrl_grp,
    product_hierarchy as lvl_7_cd,
    division as division_cd,
    industry_sector,
    base_unit as base_uom,
    purchase_order_quantity_unit as prchs_ordr_uom,
    net_weight,
    gross_weight,
    weight_unit as wgt_unit_cd,
    material_volume as mtrl_vol,
    volume_unit as vol_unit_cd,
    size_or_dimension_text as size_dim,
    unit_specific_product_length as mtrl_length,
    unit_specific_product_width as mtrl_wdth,
    unit_specific_product_height as mtrl_hgt,
    cross_plant_status as x_plnt_mtrl_sts,
    cross_plant_status_validity_date as x_plnt_mtrl_sts_dt,
    is_marked_for_deletion as deletion_flg,
    is_batch_management_required as batch_mgmt_ind,
    serial_no_explicitness_level as srl_nbr_lvl,
    product_standard_id as ean_upc_nbr,
    international_article_number_cat as ean_cat,
    manufacturer_number as mfg_nm,
    product_manufacturer_number as mfg_pt_nbr,
    manufacturer_part_profile as mfg_pt_prfl,
    country_of_origin_material as cntry_of_orgn_cd,
    commodity,
    authorization_group as auth_grp,
    item_category_group as gnrl_item_cat_grp,
    pack_code as pckng_cd,
    mater_grp_pckg_mater as pkgng_mtrl_grp,
    pckg_matertyp as pkgg_mtrl_tp,
    label_type as lbl_tp,
    label_form as lbl_form,
    handling_unit_type as hndlng_unit_tp,
    storage_condition as strg_cndtn,
    storage_percentage as strg_pctg,
    temperature_condition_indicator as tmptr_cndtn_ind,
    container_requirements as cntnr_rqrmnts,
    total_shelf_life as tot_shlf_lf,
    min_remaining_shelf_life as min_shlf_lf,
    round_rule_calculation_sled as sled_rndng_rule,
    product_indicator_expiry_date as sled_period_ind,
    approved_batch_record_required as aprvd_btch_rcrd_ind,
    hazard_material_number as hzrds_mtrl_nbr,
    document_number_without_document_management_system as dcmnt_nbr,
    document_type_without_document_management_system as dcmnt_tp,
    document_version_without_document_management_system as dcmnt_vrsn,
    document_change_number_without_document_management_system as dcmnt_chng_nbr,
    page_number_document_without_document_management_system as dcmnt_pg_nbr,
    page_format_product_memo as pg_format,
    lab_design_office as lab_dsgn_ofc,
    cad_indicator as cad_ind,
    maintenance_status as maint_status,
    material_qualification_discount_kind as mtrl_dscnt_ind,
    variable_purchase_order_unit_is_active as prchs_ordr_unit_ind,
    purchasing_value_key as prchsg_value_key,
    material_freight_group as mtrl_frt_grp,
    product_measurement_unit as uod_value,
    environment_relevant as envmnt_rlvnt_ind,
    industry_standard_name as industry_std_desc,
    quantity_goods_receipt_slips as gr_gl_slips,
    indicator_in_bulk_liquid as bulk_lqd_ind,
    indicator_highly_viscous as hgly_vscs_ind,
    current_timestamp as etl_load_dt
from {{ source('xml_source', 'xml_md_material_attr_txt') }}